name: Release
on: 
  workflow_dispatch:
    inputs:
      ReleaseHeader:
        description: The header to be added to the release.
        required: false
jobs:
  Release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Variables
        run: |
          "BARE_REPOSITORY=$($env:GITHUB_REPOSITORY.split("/")[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          $ModuleManifest = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Include *.psm1 -Recurse
          "MODULE_PATH=$($ModuleManifest.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14
      - name: Update Changelog
        id: changelog
        uses: natescherer/changelog-management-action@v1
        with:
          mode: release
          releaseVersion: ${{ steps.gitversion.outputs.SemVer }}
      - name: Update PowerShell Metadata
        uses: natescherer/update-powershell-metadata-action@v2
        with:
          path: src
          version: ${{ steps.gitversion.outputs.SemVer }}
          copyright: (c) YYYY Nate Scherer. All rights reserved.
          releaseNotes: ${{ steps.changelog.outputs.releasenotes }}
          functionsToExportPath: src\public
          description: ${{ steps.metadata.outputs.description }}
      - name: Generate Markdown Help Files
        run: |
          $DocsPath = Join-Path $env:GITHUB_WORKSPACE docs
          if (Test-Path -Path $DocsPath) {
            $CleanPath = Join-Path $DocsPath "*"
            Remove-Item -Path $CleanPath
          } else {
            New-Item -Path $DocsPath -ItemType Directory | Out-Null
          }
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module -Name platyPS
          Get-Module -Name $env:BARE_REPOSITORY -All | Remove-Module -Force -ErrorAction Ignore
          Import-Module -Name $env:MODULE_PATH -Force -ErrorAction Stop
          New-MarkdownHelp -Module $env:BARE_REPOSITORY -OutputFolder $DocsPath | Out-Null
      - name: Create Documentation for Release
        uses: natescherer/markdown-to-html-with-github-style-action@v1.1.0
        with:
          path: README.md,CHANGELOG.md,docs
          outputpath: out
          matchpathstructure: true
      - name: Compress module for GitHub release
        id: compress
        run: |
          $CopySourcePath = Join-Path $env:GITHUB_WORKSPACE "src" "*"
          $CopyDestPath = Join-Path $env:GITHUB_WORKSPACE "out"
          Copy-Item -Path $CopySourcePath -Destination $CopyDestPath -Recurse
          $ZipSourcePath = Join-Path $CopyDestPath "*"
          $ZipDestPath = Join-Path $env:GITHUB_WORKSPACE "out" "$env:BARE_REPOSITORY-v$env:GITVERSION_SEMVER.zip"
          Compress-Archive -Path $ZipSourcePath -DestinationPath $ZipDestPath
          "ZipPath=$ZipDestPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      - name: Push SemVer Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.gitversion.outputs.SemVer }}
      - name: Commit Changes to Repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Release v${{ steps.gitversion.outputs.SemVer }}
          file_pattern: ":!test\\* :!test/*"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.gitversion.outputs.SemVer }}
          tag_name: v${{ steps.gitversion.outputs.SemVer }}
          files: ${{ steps.compress.outputs.ZipPath }}
          body: |
            # Release v${{ steps.gitversion.outputs.SemVer }}
            ${{ github.event.inputs.ReleaseHeader}}

            ## Changes
            ${{ steps.changelog.outputs.releasenotes }}
      - name: Publish Module to Gallery
        uses: natescherer/publish-powershell-action@v1
        with:
          token: ${{ secrets.POWERSHELLGALLERY_KEY }}
          target: gallery
          path: out